### ISSUE TITLE
Add index.html to AdvancedPager

### ISSUE THREAD

**Issue by burkeholland** [kendo-labs/kendo-plugins#2]
Can you add an index.html file with a simple demo of the AdvancedPager?  If this functionality is already in place out of the box in the current version of Kendo UI, lets remove this plugin.  I suspect it is, but I'm not sure if your plugin still provides some extra value that people would find helpful.

**Comment by ghost** [comment]
The functionality is already implemented with the last version of KendoUI. This plugin is not necessary any more. I've removed it from my project.

**Comment by burkeholland** [comment]
Thanks for the contribution in the first place! Please feel free to contribute again if you see the need.
